version: "3.8"
   
services:
  db:
    image: postgres:13.0-alpine
    container_name: ${DB_HOST}
    restart: always
    volumes:
      - myPostgres:/var/lib/postgresql/data
      - ./db/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql:ro
    environment:
      - POSTGRES_DB=${DB_NAME}    
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432"
    logging:
      driver: json-file      
  web:
    build: .
    container_name: web
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:${WEB_PORT}"]
    restart: always
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - APP_DB_NAME=${DB_NAME}
      - APP_DB_USER=${DB_USER}
      - APP_DB_PASSWORD=${DB_PASS}
      - APP_DB_HOST=${DB_HOST}
      - APP_DB_PORT=5432         
    depends_on:
      - db
    logging:
      driver: json-file
volumes:
  myPostgres:
    name: myPostgres