{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ include "todos-chart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dev.{{ .Values.ingress.externalIP }}.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "todos-chart.fullname" . }}
            port:
              number: {{ .Values.deploy.port }}
{{- end }}              

