apiVersion: v1
kind: ConfigMap
metadata:
  name: config-postgres
data:
  postgres_database: todo
  postgres_user: docker
  postgres_password: docker  
  create_table.sql: |
    CREATE TABLE IF NOT EXISTS todos_todo (
      id serial NOT NULL,
      content text NOT NULL,
      PRIMARY KEY (id) 
    );